# Generated by Django 4.2.16 on 2026-04-05 12:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('weather', models.CharField(blank=True, choices=[('ensoleille', 'Ensoleillé'), ('nuageux', 'Nuageux'), ('pluvieux', 'Pluvieux'), ('venteux', 'Venteux'), ('orageux', 'Orageux')], max_length=20)),
                ('temperature', models.SmallIntegerField(blank=True, null=True)),
                ('workers_count', models.PositiveSmallIntegerField(default=0)),
                ('work_done', models.TextField()),
                ('materials_used', models.TextField(blank=True)),
                ('progress_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de chantier',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('project_type', models.CharField(choices=[('batiment', 'Bâtiment'), ('route', 'Route/VRD'), ('aep', "Adduction d'eau potable (AEP)"), ('assainissement', 'Assainissement'), ('pont', 'Pont'), ('hydraulique', 'Hydraulique'), ('electricite', 'Électricité'), ('autre', 'Autre')], default='batiment', max_length=20)),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé')], default='planifie', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geofence_radius', models.PositiveIntegerField(default=200, help_text='Alerter si pointage > N mètres du site. Défaut: 200m.', verbose_name='Rayon de géofencing (mètres)')),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name="Maître d'ouvrage")),
                ('client_contact', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget prévisionnel (FCFA)')),
                ('actual_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dépenses réelles (FCFA)')),
                ('progress_pct', models.PositiveSmallIntegerField(default=0, verbose_name='Avancement global (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.company', verbose_name='Entreprise')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_retard', 'En retard'), ('suspendu', 'Suspendu')], default='a_faire', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reports/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.dailyreport')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('fournisseur', models.CharField(blank=True, max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_commande', models.DateField()),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('commande', 'Commandé'), ('livre', 'Livré'), ('annule', 'Annulé'), ('en_attente', 'En attente')], default='commande', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='projects.project')),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('intemperie', 'Intempérie'), ('panne', 'Panne machine'), ('accident', 'Accident de travail'), ('retard', 'Retard livraison'), ('securite', 'Problème sécurité'), ('autre', 'Autre')], max_length=20)),
                ('severity', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé'), ('critique', 'Critique')], default='moyen', max_length=10)),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='projects.dailyreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('chef_projet', 'Chef de Projet'), ('chef_chantier', 'Chef de Chantier'), ('chef_equipe', "Chef d'Équipe"), ('ingenieur', "Ingénieur / Bureau d'Études"), ('qhse', 'Responsable QHSE'), ('magasinier', 'Magasinier'), ('comptable', 'Comptable / Financier'), ('client', "Client / Maître d'Ouvrage")], default='chef_chantier', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_added', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du projet',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('project', 'report_date')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('in', 'Entrée (Matin)'), ('out', 'Sortie (Soir)')], max_length=3, verbose_name='Type de pointage')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude GPS')),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude GPS')),
                ('distance_from_site', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Distance du site (m)')),
                ('is_off_site', models.BooleanField(default=False, help_text='Pointage effectué à plus de N mètres du chantier.', verbose_name='Hors Site')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='projects.project', verbose_name='Projet / Chantier')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Pointé par')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.worker', verbose_name='Ouvrier')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'timestamp'], name='projects_at_project_9c9cc5_idx'), models.Index(fields=['worker', 'timestamp'], name='projects_at_worker__15be31_idx'), models.Index(fields=['is_off_site'], name='projects_at_is_off__9af7cb_idx')],
            },
        ),
    ]
