# Generated by Django 4.2.16 on 2026-04-11 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='contracts/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.IntegerField(default=0)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('summary_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_processing', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrat',
                'ordering': ['-created_at'],
            },
        ),
    ]
