# Generated by Django 4.2.16 on 2026-04-11 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.project', verbose_name='Projet associé'),
        ),
        migrations.AddField(
            model_name='contract',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par'),
        ),
        migrations.AddField(
            model_name='contract',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
