# Generated by Django 4.2.16 on 2026-04-05 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction / Poste')),
                ('avatar', models.URLField(blank=True, null=True)),
                ('platform_role', models.CharField(choices=[('app_owner', 'App Owner (Super Admin Plateforme)'), ('admin_entreprise', 'Administrateur Entreprise (Directeur)'), ('office_admin', 'Administrateur de Bureau'), ('chef_projet', 'Chef de Projet'), ('chef_chantier', 'Chef de Chantier'), ('chef_equipe', "Chef d'Équipe"), ('ingenieur', "Ingénieur / Bureau d'Études"), ('qhse', 'Responsable QHSE'), ('magasinier', 'Magasinier / Stock Manager'), ('comptable', 'Comptable / Financier'), ('client', "Client / Maître d'Ouvrage")], default='chef_chantier', max_length=20, verbose_name='Rôle sur la plateforme')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Raison sociale')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country', models.CharField(default='Sénégal', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.URLField(blank=True, null=True)),
                ('subscription', models.CharField(choices=[('trial', 'Essai gratuit'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('trade', models.CharField(choices=[('maconnerie', 'Maçonnerie'), ('ferraillage', 'Ferraillage'), ('coffrage', 'Coffrage'), ('carrelage', 'Carrelage'), ('peinture', 'Peinture'), ('plomberie', 'Plomberie'), ('electricite', 'Électricité'), ('menuiserie', 'Menuiserie'), ('manoeuvre', 'Manœuvre'), ('conducteur', "Conducteur d'engin"), ('autre', 'Autre')], default='manoeuvre', max_length=20)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux journalier (FCFA)')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name="N° CNI / Pièce d'identité")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='users.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ouvrier',
                'verbose_name_plural': 'Ouvriers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('verify', 'Vérification email'), ('reset', 'Réinitialisation mot de passe'), ('invite', 'Invitation membre')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
